setProject(
[
  {
    "name":"Project",
    "linker":linker.self,
    "packages":{
      "name":"",
      "leaf":true,
      "children":[
        {
          "name":"dummy",
          "leaf":true
        },
        {
          "name":"a",
          "children":[
            {
              "name":"b",
              "leaf":"true"
            }
          ]
        }
      ]
    }
  },
  {
    "name":"JavaSE",
    "linker":linker.javadoc,
    "baseURL":"http://java.sun.com/j2se/1.5.0/docs/api/",
    "packages":{
      "name":"",
      "children":[
        {
          "name":"java",
          "children":[
            {
              "name":"lang",
              "leaf":true
            },
            {
              "name":"io",
              "leaf":true
            }
          ]
        }
      ]
    }
  }
]);
