package sorcerer.client.data;

import sorcerer.client.js.JsFunction;

/**
 * AST, which is an cryptic encoded function generated by sorcerer.
 *
 * @author Kohsuke Kawaguchi
 */
public final class AST extends JsFunction {
    protected AST() {}

    /**
     * Accepts a visitor and calls its corresponding methods.
     */
    public void accept(ASTVisitor visitor) {
        // wrap the visitor into the form suitable for 'f' of with(f) {...} call
        Parser p = Parser.create(visitor);
        // this evaluates the encoded function, which returns a new function tree
        JsFunction f = this.invoke(p);
        // and this actually fires off events to the visitor.
        f.invoke();
    }
}
