// dummy file
setProjectUsage(
[
  {
    "package":"",
    "classes":[
      "AnotherLocal",
      "PrivateClass",
      "TestCode",
      "TestCode.Base",
      "TestCode.Derived",
      "TestCode.Derived2",
      "TestCode.Inner"
    ]
  },
  {
    "package":"a.b",
    "classes":[
      "En",
      "MyWay",
      "X"
    ]
  },
  {
    "package":"java.io",
    "classes":[
      "PrintStream"
    ]
  },
  {
    "package":"java.lang",
    "classes":[
      "Class",
      "Comparable",
      "Deprecated",
      "Enum",
      "Object",
      "Runnable",
      "String",
      "System",
      "UnsupportedOperationException"
    ]
  },
  {
    "package":"java.lang.annotation",
    "classes":[
      "Documented",
      "ElementType",
      "Target"
    ]
  },
  {
    "package":"java.util",
    "classes":[
      "ArrayList",
      "Date",
      "List",
      "Map",
      "Map.Entry",
      "Random",
      "TreeMap"
    ]
  },
  {
    "package":"org.jvnet.sorcerer",
    "classes":[
      "ReservedWords"
    ]
  }
])
